
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jun 30 23:40:35 CEST 2018
//----------------------------------------------------

package syntactical;

/** CUP generated class containing symbol constants. */
public class SintacticSym {
  /* terminals */
  public static final int SEP = 5;
  public static final int WILDCARD = 44;
  public static final int POR = 32;
  public static final int PCI = 7;
  public static final int TIPVAR = 3;
  public static final int ARRAY = 4;
  public static final int SALIMPLFUNC = 16;
  public static final int FIN = 25;
  public static final int REF = 26;
  public static final int ENTRTIPFUNC = 13;
  public static final int PARAM = 19;
  public static final int NUMENT = 43;
  public static final int IGUAL = 33;
  public static final int BOOL = 28;
  public static final int DIS = 40;
  public static final int IF = 20;
  public static final int IDV = 42;
  public static final int EOF = 0;
  public static final int MAYOROIGUAL = 37;
  public static final int TRUE = 45;
  public static final int error = 1;
  public static final int RESULTADO = 17;
  public static final int MENOS = 31;
  public static final int MENOR = 35;
  public static final int NULL = 27;
  public static final int CORCHAPERTURA = 9;
  public static final int SALTIPFUNC = 14;
  public static final int PRINCFUN = 12;
  public static final int DECLVAR = 2;
  public static final int CON = 41;
  public static final int MENOROIGUAL = 36;
  public static final int MAYOR = 34;
  public static final int ENT = 29;
  public static final int PAP = 6;
  public static final int NEG = 39;
  public static final int ELSE = 21;
  public static final int DIMSEP = 8;
  public static final int ENTRIMPLFUNC = 15;
  public static final int WHILE = 22;
  public static final int ACCESO = 23;
  public static final int LLAMADA = 18;
  public static final int ASIGN = 11;
  public static final int DIFF = 38;
  public static final int FALSE = 46;
  public static final int CIERRE = 24;
  public static final int CORCHCIERRE = 10;
  public static final int MAS = 30;
}

